version: '3.1'
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes: 
     - ./pgdata:/var/lib/postgresql/data
     - /etc/localtime:/etc/localtime:ro
    environment:
      POSTGRES_PASSWORD: 123qweRTY

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin@topaz.company.ko
      - PGADMIN_DEFAULT_PASSWORD=123qweRTY
    links:
      - db
