version: '3.1'
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes: 
     - ./pgdata:/var/lib/postgresql/data
     - /etc/localtime:/etc/localtime:ro
    environment:
      POSTGRES_PASSWORD: 123qweRTY
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
